### ISSUE TITLE
No module named 'complete'

### ISSUE THREAD

**Issue by ndphuong** [buiquangmanhhp1999/extract-information-from-identity-card#4]
When I run last step: **python3 server.py**
It show error:

```
Traceback (most recent call last):
  File "server.py", line 4, in <module>
    from serve_model import *
  File "/home/python/extract-information-from-identity-card/complete/serve_model.py", line 4, in <module>
    from merged_model import CompletedModel
  File "/home/python/extract-information-from-identity-card/complete/merged_model.py", line 1, in <module>
    from complete.detector import Detector
ModuleNotFoundError: No module named 'complete'
```

I'm using python3, already install uvicorn and fastapi

**Comment by buiquangmanhhp1999** [comment]
This problem can be wrong path, you can delete "complete" and then modify path in your local computer
